---
- name: Listen for events on a webhook
  hosts: localhost

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Update prod servers
      condition: event.payload.message == "force-update"

  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: Update packages on prod servers
          organization: Home Lab

