---
- name: Listen for events on a webhook
  hosts: localhost

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  ## Define the conditions we are looking for

  rules:
    - name: Webhook Event from Mattermost
      condition: event.payload.channel_name  == "town-square" and event.payload.trigger_word == "update-my-servers"

  ## Define the action we should take should the condition be met

      actions:
        - debug:
            msg: "Got the server update hook!"
        - run_job_template:
            name: Update packages on prod servers
            organization: Home Lab

