---
- name: Listen for events on a webhook
  hosts: localhost

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 7000

  ## Define the conditions we are looking for

  rules:
    - name: Update prod servers
      condition: event.payload.message == "send-message"

  ## Define the action we should take should the condition be met

      actions:
        - debug:
            msg: "Send a message to Mattermost"
        # Just picking a random job template in my controller
        - run_job_template:
            name: Send Mattermost Message
            organization: Home Lab
