---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Print payload message to log file
      condition: event.payload is defined
      action:
        run_playbook:
          name: ansible.builtin.debug
          module_args:
            msg: "{{ event.payload }}"
