---
- name: Write webhook messages to log file
  hosts: all
  gather_facts: true
  become: true
  become_user: student
  vars:
    timestamp: "{{ ansible_facts['date_time']['iso8601'] }}"
  tasks:
    - name: Append the incoming POST message to the log file
      ansible.builtin.lineinfile:
        path: /home/student/webhook.log
        line: "{{ timestamp }} {{ message }}"
        create: true
        mode: '0644'
